apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-component1-lib
spec:
  type: website
  system: notifications
  owner: group:default/digitalservicing
  lifecycle: experimental
  providesApis:
    - api:default/Api1
  consumesApis:
    - api:default/api3
  dependsOn:
    - resource:default/resource-1
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Api1
  description: API provided by demo-component1-lib
spec:
  type: openapi
  owner: group:default/digitalservicing
  lifecycle: experimental
  system: notifications
  definition: |
    openapi: 3.0.0
    info:
      title: Api1
      version: 1.0.0
    paths:
      /demo/example:
        get:
          summary: Example endpoint
          responses:
            '200':
              description: success
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api3
  description: API consumed by demo-component1-lib
spec:
  type: graphql
  owner: group:default/digitalservicing
  lifecycle: experimental
  system: notifications
  definition: |
    schema {
      query: Query
    }

    type Query {
      hello: String
    }
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: resource-1
  description: Resource of demo-component1
spec:
  type: websites3-bucket
  owner: group:default/digitalservicing
  lifecycle: production
  system: examples
